/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        forge: {
          // Tema scuro (default .dark)
          bg:             "#101512",
          surface:        "#161D19",
          "surface-raised":"#1E2922",
          border:         "#2A3830",
          // Tema chiaro (default senza .dark)
          "light-bg":          "#F4FAF7",
          "light-surface":     "#FFFFFF",
          "light-surface-raised":"#EBF5EF",
          "light-border":      "#C8E0D4",
          "light-text-primary":  "#0E1A13",
          "light-text-secondary":"#2D5040",
          "light-text-muted":    "#6B9680",
          accent: {
            DEFAULT: "#10B981",
            soft:    "#34D399",
            dim:     "#D1FAE5",
            "dim-dark": "#1C3329",
          },
          info: {
            DEFAULT: "#3B82F6",
            soft:    "#60A5FA",
            dim:     "#DBEAFE",
            "dim-dark":"#1E2A3D",
          },
          text: {
            primary:   "#F3F6F4",
            secondary: "#9CA8A1",
            muted:     "#5E6E66",
          },
          danger:  "#EF4444",
          warning: "#F59E0B",
        },
      },
      fontFamily: {
        display: ["Fraunces", "serif"],
        body:    ["Inter", "sans-serif"],
        mono:    ["JetBrains Mono", "monospace"],
      },
      borderRadius: {
        sm: "6px",
        md: "10px",
        lg: "18px",
        xl: "24px",
      },
      keyframes: {
        "node-pulse":    { "0%,100%":{ opacity:"0.35", transform:"scale(1)" }, "50%":{ opacity:"1", transform:"scale(1.15)" } },
        "flow-dash":     { to:{ strokeDashoffset:"-24" } },
        "fade-up":       { "0%":{ opacity:"0", transform:"translateY(20px)" }, "100%":{ opacity:"1", transform:"translateY(0)" } },
        "fade-in":       { "0%":{ opacity:"0" }, "100%":{ opacity:"1" } },
        "float":         { "0%,100%":{ transform:"translateY(0)" }, "50%":{ transform:"translateY(-10px)" } },
        "blob":          { "0%,100%":{ borderRadius:"60% 40% 30% 70% / 60% 30% 70% 40%" }, "50%":{ borderRadius:"30% 60% 70% 40% / 50% 60% 30% 60%" } },
        "gradient-pan":  { "0%":{ backgroundPosition:"0% 50%" }, "50%":{ backgroundPosition:"100% 50%" }, "100%":{ backgroundPosition:"0% 50%" } },
        "spin-slow":     { to:{ transform:"rotate(360deg)" } },
        "shimmer":       { "0%":{ backgroundPosition:"-200% 0" }, "100%":{ backgroundPosition:"200% 0" } },
        "slide-down":    { "0%":{ opacity:"0", transform:"translateY(-10px)" }, "100%":{ opacity:"1", transform:"translateY(0)" } },
        "scale-in":      { "0%":{ opacity:"0", transform:"scale(0.9)" }, "100%":{ opacity:"1", transform:"scale(1)" } },
        "glow-pulse":    { "0%,100%":{ boxShadow:"0 0 20px rgba(16,185,129,0.2)" }, "50%":{ boxShadow:"0 0 40px rgba(16,185,129,0.5)" } },
      },
      animation: {
        "node-pulse":    "node-pulse 2.4s ease-in-out infinite",
        "flow-dash":     "flow-dash 1.2s linear infinite",
        "fade-up":       "fade-up 0.6s cubic-bezier(0.16,1,0.3,1) forwards",
        "fade-in":       "fade-in 0.5s ease forwards",
        "float":         "float 5s ease-in-out infinite",
        "float-slow":    "float 7s ease-in-out infinite",
        "blob":          "blob 8s ease-in-out infinite",
        "gradient-pan":  "gradient-pan 8s ease infinite",
        "spin-slow":     "spin-slow 20s linear infinite",
        "shimmer":       "shimmer 2.5s linear infinite",
        "slide-down":    "slide-down 0.3s ease forwards",
        "scale-in":      "scale-in 0.4s cubic-bezier(0.16,1,0.3,1) forwards",
        "glow-pulse":    "glow-pulse 2s ease-in-out infinite",
      },
      backgroundSize: { "200%": "200% 200%" },
    },
  },
  plugins: [],
};
